# development:
#     uri: http://chef:4000/
#     client_name: gecos-kitchen
#     keyfile: config/chef/kitchen.pem
development:
    uri: http://chef:4000/
    client_name: kk
    keyfile: config/chef/kk.pem
    couchdb: http://chef:5984/chef/

production:
    uri: http://chef:4000/
    client_name: kk
    keyfile: config/chef/kk.pem
    couchdb: http://chef:5984/chef/

pre:
    uri: https://10.240.194.220/
    client_name: kitchen2
    keyfile: config/chef/kitchen2.pem
    couchdb: http://chef:5984/chef/
